KButterfly_Effect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainpage, name="mainpage"),
    path("index/", index, name="index"),
    path("about/",about, name="about"),
    path("contact/",contact, name="contact"),
    path('posts/', include('posts.urls')),
    path('users/',include('users.urls')),
    path("accounts/", include("allauth.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *


app_name = 'posts'
urlpatterns = [
   
    path("postlist/<int:arrange>/",postlist, name="postlist"),
    path('new_post/',new_post,name="new_post"),
    path('create/',create,name="create"),
    path('detail/<int:id>/',detail,name="detail"),
    path('edit_post/<int:id>/',edit_post,name="edit_post"),
    path('update/<int:id>/',update,name="update"),
    path('delete/<int:id>/',delete,name="delete"),
    path('like_toggle/<int:post_id>/',like_toggle, name="like_toggle"),

]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("mypage/", mypage, name="mypage"),
    path("makelist/",makelist,name="makelist"),
    path("deletelist/",deletelist,name="deletelist"),
    path("updatelist/<int:id>/",updatelist,name="updatelist"),
    path("addlist/<int:post_id>/",addlist,name="addlist"),
    path("todolist/<int:arrange>/",todolist,name="todolist"),
    path("introduce/", introduce, name="introduce"),
    path("<int:id>/posts/", user_posts, name="user_posts"),
    path("edit/", edit, name="edit"),
    path("update/", update, name="update"),
    path("fin/<int:id>/",fin,name="fin"),
]

KButterfly_Effect/views.py
from django.shortcuts import render
from posts.models import Post
from django.contrib.auth.models import User

from users.models import Profile
# Create your views here.
def index(request):
    a = list(Post.objects.all().order_by("?")) # 랜덤 정렬
    a2 = a[:2]

    b = list(Post.objects.all().order_by('-like')) # 좋아요 순 정렬
    b3 = b[:3]

    top=Profile.objects.all().order_by('-personal_eco_point')
    top4=top[:4]

    context = {
        "a2":a2,
        "b3":b3,
        "top4":top4,
    }
    return render(request, "index.html", context)

def about(request):
    return render(request, "main/about.html")

def contact(request):
    return render(request, "main/contact.html")

def mainpage(request):
    return render(request, "main/mainpage.html")

KButterfly_Effect/templates/shared/footer.html
{% load static %}
<div class="site-section subscribe bg-light">
  <div class="container">
    <form action="#" class="row align-items-center">
      <div class="col-md-5 mr-auto">
        <h2>Newsletter Subcribe</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis aspernatur ut at quae omnis pariatur
          obcaecati possimus nisi ea iste!</p>
      </div>
      <div class="col-md-6 ml-auto">
        <div class="d-flex">
          <input type="email" class="form-control" placeholder="Enter your email">
          <button type="submit" class="btn btn-secondary"><span class="icon-paper-plane"></span></button>
        </div>
      </div>
    </form>
  </div>
</div>



<div class="footer">
  <div class="container">


    <div class="row">
      <div class="col-12">
        <div class="copyright">
          <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>
              document.write(new Date().getFullYear());
            </script> All rights reserved | This template is made with <i class="icon-heart text-danger"
              aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

KButterfly_Effect/templates/shared/navbar.html
{% load static %}

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300" style="margin-bottom: 30px;">

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-lg-6 d-flex">
            <img src="{% static 'images/logo1.png' %}" height="50" width="50">
            <a href="{% url 'index' %}" class="site-logo">
              Butterfly Effect
            </a>

            <a href="#" class="ml-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h3"></span></a>

          </div>
          <div class="col-12 col-lg-6 ml-auto d-flex">
            {% comment %} <div class="ml-md-auto top-social d-none d-lg-inline-block">
                <a href="#" class="d-inline-block p-3"><span class="icon-facebook"></span></a>
                <a href="#" class="d-inline-block p-3"><span class="icon-twitter"></span></a>
                <a href="#" class="d-inline-block p-3"><span class="icon-instagram"></span></a>
            </div> {% endcomment %}
            {% comment %} <form action="#" class="search-form d-inline-block">

              <div class="d-flex">
                <input type="email" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-secondary"><span class="icon-search"></span></button>
              </div>
            </form> {% endcomment %}


          </div>
          <div class="col-6 d-block d-lg-none text-right">

          </div>
        </div>
      </div>

      <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">

        <div class="container">
          <div class="d-flex align-items-center">

            <div class="mr-auto">
              <nav class="site-navigation position-relative text-right" role="navigation">
                <ul class="site-menu main-menu js-clone-nav mr-auto d-none pl-0 d-lg-block">
                  <li class="active">
                    <a href="{% url 'index' %}" class="nav-link text-left">Home</a>
                  </li>
                  <li>
                    <a href="{% url 'posts:postlist' 1 %}" class="nav-link text-left">Ecolist</a>
                  </li>
                  <li>
                    <a href="{% url 'about' %}" class="nav-link text-left">About</a>
                  </li>

                  <li>
                    <a href="{% url 'contact' %}" class="nav-link text-left">Contact</a>
                  </li>

                  {%if request.user.is_authenticated%}
                  <li><a href="{% url 'users:mypage' %}" class="nav-link text-left">Mypage</a></li>
                  <li><a href="{% url 'users:todolist' 1 %}" class="nav-link text-left">Todolist</a></li>
                  <li><a href="{% url 'account_logout' %}" class="nav-link text-left">Logout</a></li>
                  {%else%}
                  <li><a href="{% url 'account_login' %}" class="nav-link text-left">Login</a></li>
                  <li><a href="{% url 'account_signup' %}" class="nav-link text-left">Signup</a></li>
                  {%endif%}

                </ul>
              </nav>

            </div>

          </div>
        </div>

      </div>

    </div>
  </div>
</body>