KButterfly_Effect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainpage, name="mainpage"),
    path("index/", index, name="index"),
    path("about/",about, name="about"),
    path("contact/",contact, name="contact"),
    path('posts/', include('posts.urls')),
    path('users/',include('users.urls')),
    path("accounts/", include("allauth.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *


app_name = 'posts'
urlpatterns = [
   
    path("postlist/<int:arrange>/",postlist, name="postlist"),
    path('new_post/',new_post,name="new_post"),
    path('create/',create,name="create"),
    path('detail/<int:id>/',detail,name="detail"),
    path('edit_post/<int:id>/',edit_post,name="edit_post"),
    path('update/<int:id>/',update,name="update"),
    path('delete/<int:id>/',delete,name="delete"),
    path('like_toggle/<int:post_id>/',like_toggle, name="like_toggle"),

]

KButterfly_Effect/views.py
from django.shortcuts import render
from posts.models import Post
from django.contrib.auth.models import User

from users.models import Profile
# Create your views here.
def index(request):
    a = list(Post.objects.all().order_by("?")) # 랜덤 정렬
    a2 = a[:2]

    b = list(Post.objects.all().order_by('-like')) # 좋아요 순 정렬
    b3 = b[:3]

    top=Profile.objects.all().order_by('-personal_eco_point')
    top4=top[:4]

    context = {
        "a2":a2,
        "b3":b3,
        "top4":top4,
    }
    return render(request, "index.html", context)

def about(request):
    return render(request, "main/about.html")

def contact(request):
    return render(request, "main/contact.html")

def mainpage(request):
    return render(request, "main/mainpage.html")

KButterfly_Effect/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
  <title>나비효과 &mdash; 나를 통해서 비로소 지켜지는 환경</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- 카카오톡 미리보기 썸네일 이미지와 내용 -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://kbutterfly-effect.herokuapp.com/">
  <meta property="og:title" content="나비효과: 나를 통해서 비로소 지켜지는 환경">
  <meta property="og:image" content="https://kbutterfly-effect.herokuapp.com/static/images/logo1.png">
  <meta property="og:description" content="할일 추천을 통해 만들어간 Todolist로 나도 모르게 자연을 지키게 되는 나비효과">


  <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cabin:400,700&display=swap" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"> <!--CDN 링크 --> </head>

  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  
  {% include 'shared/navbar.html' %}
  
  {% block content %}

  {% endblock content %}

    <!-- loader -->
  <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#ff5e15"/></svg></div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <script src="{% static 'js/jquery.mb.YTPlayer.min.js' %}"></script>




  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

KButterfly_Effect/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="site-section py-0">
  <div class="owl-carousel hero-slide owl-style">

    {% for a in a2 %}
    <div class="site-section">
      <div class="container">
        <div class="half-post-entry d-block d-lg-flex bg-light">
          <div class="img-bg"
          {% if a.image %}
          style="background-image: url({{a.image.url}})"
          {% else %}
          style="background-image: url({% static 'images/d2.jpg' %})"
          {% endif %}
          ></div>
          <div class="contents">
            <span class="caption">{{a.title_tag}}</span>
            <h2><a href="{% url "posts:detail" a.id %}">{{a.title}}</a></h2>
            <p class="mb-3"
            style="
              overflow: hidden;
              text-overflow: ellipsis;
              display: -webkit-box;
              -webkit-line-clamp: 5; /* 라인수 */
              -webkit-box-orient: vertical;
              word-wrap:break-word; 
              line-height: 1.2em;
              height: 6em; /* line-height 가 1.2em 이고 5라인을 자르기 때문에 height는 1.2em * 5 = 6em */">
              {{a.body}}
            </p>
            <div class="post-meta">
              <span class="d-block"><a href="#">{{a.writer}}</a></span>
              <span class="date-read">마감: {{a.deadline}}<span class="mx-1">&bullet;</span>{{a.shared}}명이 TODOLIST에 담아갔어요</span>
            </div>

          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<section class="pt-4" id="team">

  <div class="container">
    <div class="row justify-content-center mb-6">
      <div class="col-lg-6 col-xxl-5 text-center mx-auto mb-7">
        <h2 style="color:black;"><strong>이달의 환경러</strong><img src="{% static 'images/Ellipse 3.png' %}"></h2>
        <br><br>
      </div>
      <!-- <div class="section-title">
        <h2><strong>이달의 환경러</strong></h2><img src="{% static 'images/Ellipse 3.png' %}">
      </div> -->
      <div style="width: 100%; display:flex; justify-content:space-around;">
        {% for top in top4%}
          <div style="width: 20%; border-radius:80px;  height:300px; box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);">
            <div style="height:50%; border-radius: 80px 80px 0px 0px; {% if top.image %} background-size:cover; background-image: url({{top.image.url}}) {% endif %}"></div>
            <div style="display:table; width:100%; height:50%; border-radius:0 0 80px 80px; text-align:center;">
              <p style="display:table-cell; width:100%; vertical-align:middle;">
                
                <b>{{top.name}} 님</b><br>
                {{top.count}}회 활동<br>
                
              </p>
            </div>
          </div>
        {%endfor%}
      </div>
      
    </div>
  </div>
</section>









<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <div class="section-title">
          <h2><strong>환경관련 토픽</strong></h2><img src="{% static 'images/Ellipse 3.png' %}">
        </div>
        <div class="post-entry-2 d-flex">
          <div class="contents order-md-1 pl-0">
            <h2><a href="https://www.news1.kr/articles/?4438399">코웨이 환경기술연구소 물 연구원 15명 '워터 소믈리에' 자격 취득</a></h2>
          </div>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="contents order-md-1 pl-0">
            <h2><a href="https://view.asiae.co.kr/article/2021091609494098779">우리금융, 청소년 대상 ESG 환경교육 실시</a></h2>
          </div>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="contents order-md-1 pl-0">
            <h2><a href="https://www.pressian.com/pages/articles/2021091714021322839?utm_source=naver&utm_medium=search">강릉시, 미생물 농법으로 환경친화적 농산물 생산</a></h2>
          </div>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="contents order-md-1 pl-0">
            <h2><a href="https://newsis.com/view/?id=NISX20210915_0001584527&cID=14001&pID=14000">용인시 처인구 포곡읍에 종합환경교육센터 들어선다</a></h2>
          </div>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="contents order-md-1 pl-0">
            <h2><a href="https://cnews.pinpointnews.co.kr/view.php?ud=20210917135916540accfd60e02_45">하이트진로,必환경 시대 ... '청정리사이클' 성공적 마무리 </a></h2>
          </div>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="contents order-md-1 pl-0">
            <h2><a href="https://www.khan.co.kr/national/health-welfare/article/202109160936001">건협, 방화근린공원서 환경정화 캠페인 전개</a></h2>
          </div>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="section-title">
          <h2><strong>인기 포스팅</strong></h2><img src="{% static 'images/Ellipse 3.png' %}">
        </div>


        {% for b in b3 %}
        <div class="trend-entry d-flex">
          <div class="col-lg-4" style="background-color: #4AF08C; border-radius: 40px 0px 0px 40px">
          </div>
          <div class="col-lg-8" style="margin-top: 2%;">
            <div class="trend-contents">
              <h2><a href="{% url "posts:detail" b.id %}"><strong>{{b.title}}</strong></a></h2>
              <div class="post-meta">
                <span class="d-block"><a href="#">{{b.writer}}</a></span>
                <span class="date-read">마감: {{b.deadline}}<br>{{b.shared}}명이 TODOLIST에 담아갔어요
                <br>{{b.like_count}}명이 좋아합니다</span>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        <p>
          <a href="{% url "posts:postlist" 1 %}" class="more">See More Ecolist <span class="icon-keyboard_arrow_right"></span></a>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        {% comment %} <ul class="custom-pagination list-unstyled">
          <li><a href="#">1</a></li>
          <li class="active">2</li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
        </ul> {% endcomment %}
      </div>
    </div>
  </div>
</div>


{% endblock %}