KButterfly_Effect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainpage, name="mainpage"),
    path("index/", index, name="index"),
    path("about/",about, name="about"),
    path("contact/",contact, name="contact"),
    path('posts/', include('posts.urls')),
    path('users/',include('users.urls')),
    path("accounts/", include("allauth.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *


app_name = 'posts'
urlpatterns = [
   
    path("postlist/<int:arrange>/",postlist, name="postlist"),
    path('new_post/',new_post,name="new_post"),
    path('create/',create,name="create"),
    path('detail/<int:id>/',detail,name="detail"),
    path('edit_post/<int:id>/',edit_post,name="edit_post"),
    path('update/<int:id>/',update,name="update"),
    path('delete/<int:id>/',delete,name="delete"),
    path('like_toggle/<int:post_id>/',like_toggle, name="like_toggle"),

]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("mypage/", mypage, name="mypage"),
    path("makelist/",makelist,name="makelist"),
    path("deletelist/",deletelist,name="deletelist"),
    path("updatelist/<int:id>/",updatelist,name="updatelist"),
    path("addlist/<int:post_id>/",addlist,name="addlist"),
    path("todolist/<int:arrange>/",todolist,name="todolist"),
    path("introduce/", introduce, name="introduce"),
    path("<int:id>/posts/", user_posts, name="user_posts"),
    path("edit/", edit, name="edit"),
    path("update/", update, name="update"),
    path("fin/<int:id>/",fin,name="fin"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    count = models.IntegerField(default=0) # 퍼온거 한횟수
    personal_eco_point= models.IntegerField(default=0) #개인 에코점수
    name = models.CharField(max_length=64, default="")
    phnum = models.CharField(max_length=12, default="")
    image = models.ImageField(upload_to="user/", null=True)

class Todolist(models.Model):
    id = models.AutoField(primary_key=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE) #작성자
    name=models.CharField(max_length=40) # 할 일 이름
    description=models.TextField() #  할 일 설명
    date_start= models.DateTimeField(auto_now=False) # 시작일
    date_deadline=models.DateTimeField(auto_now=False) # 마감일
    pub_date = models.DateTimeField(auto_now=True) # 생성일, 사용은 X
    p_or_o = models.BooleanField(default=False) # 개인이 만든건지 공식적인건지 False는 개인 True는 공식
    after=models.BooleanField(default=False) #시간이 지났거나 check를 눌렀을때

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    

users/forms.py
from django import forms
from allauth.account.forms import SignupForm

class SignupForm(SignupForm):
    name = forms.CharField(label="이름")
    phnum = forms.CharField(label="휴대폰 번호")
    image = forms.ImageField(required=True, initial="../static/images/person_1.jpg")

    def save(self, request):
        user = super(SignupForm, self).save(request)
        user.profile.name = self.cleaned_data["name"]
        user.profile.phnum = self.cleaned_data["phnum"]
        user.profile.image = self.cleaned_data["image"]
        user.save()
        return user

users/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Todolist
from posts.models import Post
# Create your views here.
from django.utils import timezone
from django.utils.timezone import timedelta
import json
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, timedelta,date
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def mypage(request):
    posts=Post.objects.filter(writer=request.user)
    return render(request, "users/mypage.html",{"posts":posts})

def todolist(request, arrange):
    user=request.user
    if arrange==1: # 1은 진행중
        now=datetime.today()
        mylist=Todolist.objects.filter(writer=user,date_deadline__gt=now).order_by('date_deadline')
    elif arrange==2: # 2은 오늘마감 보기
        now=datetime.today()
        today=date.today()
        tomorrow=date.today()+timedelta(days=1)
        mylist=Todolist.objects.filter(writer=user,date_deadline__gt=now,date_deadline__range=(today,tomorrow)).order_by('date_deadline')
    else: # 3은 지난거 보기
        now=datetime.today()
        mylist=Todolist.objects.filter(writer=user,date_deadline__lt=now).order_by('date_deadline')
    past=arrange
    
    start={}
    dead={}
    for i in mylist:
        start[i.id]=i.date_start.replace(microsecond=0).isoformat()[:-3]
        dead[i.id]=i.date_deadline.replace(microsecond=0).isoformat()[:-3]
        # print(start[i.id])
    return render(request,"users/todolist.html",{"lists":mylist,"starts":start,"deads":dead,"past":past})

@login_required
def addlist(request,post_id):
    post=get_object_or_404(Post,pk=post_id)
    post.shared+=1 # 포스트 공유 1 추가
    add_list=Todolist()
    add_list.name=post.title
    add_list.description=post.body+"\n 작성자 : "+str(post.writer)+"\n"
    # "< a href={% url 'posts:details' post.id%}>원본</a>"
    add_list.writer=request.user
    add_list.date_start=post.pub_date.replace(microsecond=0).isoformat()[:-3]
    add_list.date_deadline=post.deadline.replace(microsecond=0).isoformat()[:-3]
    add_list.pub_date=timezone.now()
    add_list.p_or_o=True
    add_list.save()
    return redirect("users:todolist",1)


def makelist(request): # 빈 투두리스트
    new_list = Todolist()
    new_list.name = ''
    new_list.description = ''
    new_list.writer = request.user
    new_list.date_start = timezone.now()
    new_list.date_deadline = timezone.now()+timedelta(hours=1)
    new_list.pub_date = timezone.now()
    # new_list.p_or_o=False #default값 있음
    new_list.save()
    return redirect("users:todolist",1)

@csrf_exempt
def updatelist(request,id): # 빈 투두리스트
    update_list = Todolist.objects.get(id=id)
    update_list.name = request.POST["name"]
    update_list.description = request.POST["description"]
    update_list.writer = request.user
    update_list.date_start = request.POST['date_start']
    update_list.date_deadline = request.POST['date_deadline']
    # print(update_list.date_start)
    update_list.pub_date = timezone.now()
    # new_list.p_or_o=False #default값 있음
    update_list.save()
    return redirect("users:todolist",1)

@csrf_exempt
def deletelist(request):
    param=json.loads(request.body)
    arr=param['checked_id']
    cnt=param['cnt']
    i=0
    
    while(i<cnt):
        deletelist=Todolist.objects.get(id=arr[i])
        deletelist.delete()
        i+=1
    if i==cnt:
        check=1
    else:
        check=0
    context={
        "check":check
    }
    
    return HttpResponse(json.dumps(context),content_type="application/json")

def introduce(request):  # 다른 사람들도 접속하면 볼 수 있는 페이지(iframe)
    return render(request, "users/introduce.html")

def user_posts(request, id):  # 다른 사람들도 접속하면 볼 수 있는 페이지(iframe)
    user = get_object_or_404(User, pk=id)
    context = {
        "user": user,
        "posts": Post.objects.filter(writer=user),
    }
    return render(request, "users/user_posts.html", context)

def edit(request):  # 개인만 쓸 페이지
    cur_user = request.user
    return render(request, "users/edit.html", {"user": cur_user})

def update(request):  # 개인만 쓸 함수
    update_profile = request.user.profile
    update_profile.name = request.POST["name"]
    update_profile.phnum = request.POST["phnum"]
    if (request.FILES.get('image')): # 이미지를 제출했을 때만 이미지 업데이트
        update_profile.image = request.FILES["image"]
    update_profile.save()
    # posts=Post.objects.all()
    return redirect("users:introduce")

def fin(request,id):
    fintodo=Todolist.objects.get(id=id)
    fintodo.after = True;
    userprofile=request.user.profile
    if fintodo.p_or_o==True:
        userprofile.count+=1
        userprofile.personal_eco_point+=1
    print(fintodo.p_or_o)
    print(userprofile.count)
    fintodo.save()
    userprofile.save()
    return redirect("users:todolist",1)

users/templates/users/edit.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div style="background-size:100%; height:600px;">
    <div style="width:50%; height:100%; margin:150px auto; ">
        <form action="{% url 'users:update' %}" method="post" enctype="multipart/form-data" style="text-align:center">
            {%csrf_token%}
            <p><h1>수정하기</h1></p>
            <p>이름 : <input type="text" name="name" value="{{user.profile.name}}" required></p>
            <p>전화번호 : <input type="text" name="phnum" value="{{user.profile.phnum}}" required></p>
            <p>프로필 사진 : <input type="file" name="image" accept="image/*"></p>
            <button type="submit">제출</button>
        </form>
    </div>
</div>

users/templates/users/introduce.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div style="background-size:100%; height:600px;">
    <div style="width:50%; height:100%; margin:150px auto; ">
        <p>정보를 수정하고 싶다면 좌측에 <b>내 정보 수정하기</b>를 눌러주세요</p>
        <p>내가 올린 글을 확인하고 싶다면 좌측에 <b>내가 올린 일</b>을 눌러주세요</p>
    </div>
</div>

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <br>
  <div style="display:flex;">
      <div style="width:50%; padding:20px; margin-top: 3%;">
          <p>
              <div style="text-align: center; padding: 10px 0;">
                  <img style="width: 30%;" src="{{user.profile.image.url}}" alt="user default image">
                  <br>
                  <br>
              </div>
              <div style="padding: 30px; border: 2px inset grey; width:100%; text-align:center; word-break:break-all;">
                      
                      <h6 style="margin-bottom:5%;">ID: {{user}}</h6>
                      <input type="button" class="btn btn-default" style="color: black; width:100%; margin-bottom: 5%;"
                          onclick="changeIframeUrl('{%url 'users:introduce'%}')" value="사용 방법"> <br>
                      <input type="button" class="btn btn-default" style="color: black; width:100%; margin-bottom: 5%;"
                          onclick="changeIframeUrl('{%url 'users:edit' %}')" value="내 정보 수정하기">
                      <input type="button" class="btn btn-default" style="color: black; width:100%; margin-bottom: 5%;"
                          onclick="changeIframeUrl('{%url 'users:user_posts' user.id%}')" value="내가 올린 일">
              </div>
          </p>
      </div>
      <div style="width:65%; padding:20px;">
          <iframe id="main_frame" name="main_frame" src="{%url 'users:introduce' %}"
              style="width:100%; height: 120%; border:none; margin-top: 20%;"></iframe>
      </div>
  </div>


<script>
  function changeIframeUrl(url)
  {
    document.getElementById("main_frame").src = url;
  }
</script>

{% endblock %}

users/templates/users/todolist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<script src="{% static 'js/jquery-latest.min.js'%}"></script>

<div class="section" style="width: 100%; margin-top:54px;">
    <br>
    <div class="img-controll" style="display: flex; width: 60%; margin:0 auto;">
        <a href="{% url 'users:makelist' %}" style="cursor:pointer; width: 4%; height: 4%; margin: 5px;"><img style="width: 100%;" src="{% static 'images/plus.svg'%}" alt="+"></a>
        <div onclick="count_check()" style="cursor:pointer; width: 4%; height: 4%; margin: 5px;"><img style="width: 100%;" src="{% static 'images/minus.svg'%}" alt="-"></div>
        
            
    </div>
    <div style="width:80%; text-align:right;">
        <a href="{% url 'users:todolist' 1 %}">진행중</a> &nbsp;
        <a href="{% url 'users:todolist' 2 %}">오늘 마감</a> &nbsp;
        <a href="{% url 'users:todolist' 3 %}">지난거</a> &nbsp;
    </div> <br>
   <div class="todolist" style="width: 60%; margin:0 auto;">
        {% for list in lists %}   
            <script>
                function printlist(){
                    var list_id={{list.id}};
                    var starts = {{starts|safe}};
                    var start=starts[list_id];
                    var deads = {{deads|safe}};
                    var dead = deads[list_id];
                    var html=`
                    <form action="{%url 'users:updatelist' list.id %}" method="post" enctype="multipart/form-data">
                    <table style=" width:100%;">
                        <tr style="width:100%;">
                            <td style="width:5%; text-align:center; "><input type="checkbox" name="check" id="${list_id}"></td>
                            <td style="width:90%; ">                                 
                                <input name="name" value="{{list.name}}" class="name${list_id}" id="name${list_id}" onclick="scroll_name(${list_id})" style="width:100%; height:50px; cursor:pointer; margin:0 auto; text-align:center; line-height:50px;">
                            </td>
                        
                            <td style=" width: 5%;">
                                <a class="check${list_id}" href="{% url 'users:fin' list.id %}" style="cursor:pointer; width: 100%; height: 100%; margin: 5px;"><img style="width: 100%;" src="{% static 'images/check.svg'%}" alt="check"></a>
                            </td>
                        </tr>
                        <tr id="des-tr${list_id}" style="display: none; width:100%;">
                            <td style="width:5%; text-align:center; "></td>
                            <td style="width:90%;">
                                <div id="description${list_id}" style="overflow:scroll; padding:15px; border:1px solid black; width:100%; height:300px; display:none;" >
                                    <textarea style="margin-bottom:10px; width:100%; height:60%;" class="description${list_id}" name="description"> {{list.description}}</textarea>
                                    <div style=" overflow:scroll;">
                                    
                                    시작 : <input type="datetime-local" class="date_start${list_id}" value="${start}" name="date_start"> <br>
                                    마감 : <input type="datetime-local" class="date_deadline${list_id}" value="${dead}" name="date_deadline"> 
                                    </div>
                                    <div style="text-align:right;">
                                    
                                    <button class="submit${list_id}" type="submit">수정</button>
                                    </div>
                                </div>
                            </td>
                            <td style="width:5%;"></td>
                        </tr>
                    </table>
                    </form>
                    <br>
                    `;
                    
                    $('.todolist').append(html);
                         
                }
                printlist();
                
                
            </script>
            <script>
                function past(){
                    var past ={{past}};
                    var list_id={{list.id}};
                    
                    if(past==3){
                        console.log(past);
                        $(`.check${list_id}`).removeAttr("href");
                    }
                    
                }
                past();
            </script>
            {% if list.after %}
                <script>
                    
                    function finish(){
                        var list_id={{list.id}};
                        $(`.name${list_id}`).attr("readonly",true);
                        $(`.name${list_id}`).css('background', 'lightgray');
                        $(`.description${list_id}`).attr("disabled",true);
                        $(`.date_start${list_id}`).attr("disabled",true);
                        $(`.date_deadline${list_id}`).attr("disabled",true);
                        $(`.submit${list_id}`).attr("disabled",true);
                            
                    }
                    
                    finish();
                </script>
            {% endif %}
        {%endfor%}
        <script>

            function scroll_name(id){
                $(`#des-tr${id}`).slideToggle('fast');   
                $(`#description${id}`).slideToggle('fast');
            }

            function count_check(){
            var cnt = $("input[name='check']:checked").length;
            var arr = new Array();
            $("input[name='check']:checked").each(function(){
                arr.push($(this).attr('id'));
                });
            var param = {'checked_id':arr,
            'cnt':cnt
            }
            if(cnt==0){
                alert("선택된 글이 없습니다 ");
            }
            else{
                
                $.ajax({
                    type:"POST",
                    url:"{% url 'users:deletelist' %}",
                    data: JSON.stringify(param),
                    dataType:"json",
                    
                    success: function(response){
                        if(response.check ==1){
                            alert("삭제 완료");
                        }
                        else{
                            alert("삭제 실패");
                        }
                    },
                    error: function(){
                        alert("서버 통신 오류");
                    }
                });
                location.reload();
            }

        }
        </script>
        
    </div>
</div>

{% endblock %}

users/templates/users/user_posts.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script language="javascript" type="text/javascript">
    function open_parent_p(t) {
        a = "../../posts/detail/" + t
        console.log(a)
        window.parent.location.href = a;
    }
</script>


<div style="background-size:100%; ">
    <br>
    <h2 style="font-family: 'Nanum Gothic Coding', sans-serif;">내가 올린 일</h2>
    
    {% for post in posts %}
    <hr>
    <div style="display:flex; margin: 10px 0px; height: 25vh;">
        <div style="overflow:hidden;margin:0px 30px;width:20vh; height:20vh; border-radius:10%;">
            {% if post.image %}
            <img src="{{ post.image.url }}" style="object-fit: cover; width:100%; height: 100%;"
            style=" border-radius:10%; background-color:lightgray; width:100%; height:100%;" alt="서잔">
            {% else %}
            <img src="{% static 'images/d2.jpg' %}" style="object-fit: cover; width:100%; height: 100%;"
            style=" border-radius:10%; background-color:lightgray; width:100%; height:100%;" alt="서잔">
            {% endif %}
        </div>
        <h3><a style="display:flex; flex-direction: column; justify-content: space-around;"
            href="" onclick="var l = open_parent_p({{post.id}})">
            {{ post.title }}
        </a></h3>
    </div>
    {% endfor %}
    <hr>
</div>