KButterfly_Effect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainpage, name="mainpage"),
    path("index/", index, name="index"),
    path("about/",about, name="about"),
    path("contact/",contact, name="contact"),
    path('posts/', include('posts.urls')),
    path('users/',include('users.urls')),
    path("accounts/", include("allauth.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *


app_name = 'posts'
urlpatterns = [
   
    path("postlist/<int:arrange>/",postlist, name="postlist"),
    path('new_post/',new_post,name="new_post"),
    path('create/',create,name="create"),
    path('detail/<int:id>/',detail,name="detail"),
    path('edit_post/<int:id>/',edit_post,name="edit_post"),
    path('update/<int:id>/',update,name="update"),
    path('delete/<int:id>/',delete,name="delete"),
    path('like_toggle/<int:post_id>/',like_toggle, name="like_toggle"),

]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("mypage/", mypage, name="mypage"),
    path("makelist/",makelist,name="makelist"),
    path("deletelist/",deletelist,name="deletelist"),
    path("updatelist/<int:id>/",updatelist,name="updatelist"),
    path("addlist/<int:post_id>/",addlist,name="addlist"),
    path("todolist/<int:arrange>/",todolist,name="todolist"),
    path("introduce/", introduce, name="introduce"),
    path("<int:id>/posts/", user_posts, name="user_posts"),
    path("edit/", edit, name="edit"),
    path("update/", update, name="update"),
    path("fin/<int:id>/",fin,name="fin"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    title_tag = models.CharField(max_length=20) # 요약 태그
    hashtag = models.TextField(max_length=30)  #해시 태그, 여러개하면 할때마다 띄워쓰기 시키기
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(auto_now=False)
    body = models.TextField()
    image = models.ImageField(upload_to="post/",null=True)
    shared= models.IntegerField(default=0) #공유된 수
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set',through='Like')
    after_dead=models.BooleanField(default=False) #데드라인이후 포스팅에 좋아요, 공유횟수가 개인 에코점수로 넘어간지 확인

    @property
    def like_count(self):
        return self.like_user_set.count()

#좋아요 모델
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.utils import timezone
import json
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta,date

# Create your views here.

def postlist(request, arrange): # post 목록
    
    if arrange==1: # 1은 진행중
        now=datetime.today()
        posts=Post.objects.filter(deadline__gt=now).order_by('deadline')
    elif arrange==2: # 2은 오늘마감 보기
        now=datetime.today()
        today=date.today()
        tomorrow=date.today()+timedelta(days=1)
        posts=Post.objects.filter(deadline__gt=now,deadline__range=(today,tomorrow)).order_by('deadline')
    else: # 3은 지난거 보기
        now=datetime.today()
        posts=Post.objects.filter(deadline__lt=now).order_by('deadline')

    hashtag_dict={}

    for i in posts:
        # print(i.hashtag)
        jd=json.decoder.JSONDecoder()
        hashtag_list=jd.decode(i.hashtag)
        hashtag_dict[i.id]=hashtag_list
    
    # print(hashtag_dict)
    return render(request, "posts/postlist.html",{"posts":posts,"hashtag":hashtag_dict})

@login_required
def new_post(request): # post 입력페이지
    return render(request, "posts/new_post.html")

def create(request): # create
    new_post = Post()
    new_post.title = request.POST["title"]
    new_post.title_tag = request.POST["title_tag"]
    hashtag=request.POST["hashtag"].split()
    new_post.hashtag = json.dumps(hashtag)
    
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.deadline = request.POST['deadline']
    new_post.body = request.POST["body"]
    new_post.image = request.FILES.get("image")
    new_post.save()
    return redirect("posts:detail", new_post.id)

@login_required
def detail(request, id): # post 세부페이지
    post = get_object_or_404(Post, pk=id)

    hashtag_dict={}
    jd=json.decoder.JSONDecoder()
    hashtag_list=jd.decode(post.hashtag)

    return render(request, "posts/detail.html", {"post": post,"hashtag":hashtag_list})

def edit_post(request, id): # post 수정페이지
    edit_post = Post.objects.get(id=id)

    hashtag_dict={}
    jd=json.decoder.JSONDecoder()
    hashtag=jd.decode(edit_post.hashtag)
    deadline=edit_post.deadline.replace(microsecond=0).isoformat()[:-3]

    return render(request, "posts/edit_post.html", {"post": edit_post,"hashtag":hashtag,"deadline":deadline})

def update(request, id): # update
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST["title"]
    update_post.title_tag = request.POST["title_tag"]
    hashtag=request.POST["hashtag"].split()
    update_post.hashtag = json.dumps(hashtag)
    
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.deadline = request.POST['deadline']
    update_post.body = request.POST["body"]
    if request.FILES.get('image'):
        update_post.image=request.FILES.get('image')
    update_post.save()
    return redirect("posts:detail", update_post.id)

def delete(request, id): # delete
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect("posts:postlist",1)

@require_POST
@login_required
def like_toggle(request,post_id):
    post=get_object_or_404(Post,pk=post_id)
    post_like,post_like_created=Like.objects.get_or_create(user=request.user,post=post)

    if not post_like_created:
        post_like.delete()
        result="like_cancel"

    else:
        result="like"

    context={
        "like_count":post.like_count,
        "result":result
    }

    return HttpResponse(json.dumps(context),content_type="application/json")

posts/templates/posts/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-9">
            <div class="section-title">
              <span class="caption d-block small">Categories</span>
              <h2>Politics</h2>
            </div>
            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_4.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_3.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_1.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_4.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_3.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                <h2><a href={% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_1.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_4.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_3.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-2" style="background-image: url({% static 'images/img_h_1.jpg' %})"></div>
              <div class="contents order-md-1 pl-0">
                
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus praesentium neque, voluptatum quam quibusdam.</p>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="section-title">
              <h2>Popular Posts</h2>
            </div>

            <div class="trend-entry d-flex">
              <div class="number align-self-start">01</div>
              <div class="trend-contents">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="trend-entry d-flex">
              <div class="number align-self-start">02</div>
              <div class="trend-contents">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="trend-entry d-flex">
              <div class="number align-self-start">03</div>
              <div class="trend-contents">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>

            <div class="trend-entry d-flex pl-0">
              <div class="number align-self-start">04</div>
              <div class="trend-contents">
                <h2><a href="{% url 'posts:blog_single' %}">News Needs to Meet Its Audiences Where They Are</a></h2>
                <div class="post-meta">
                  <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                  <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span class="icon-star2"></span></span>
                </div>
              </div>
            </div>
            
            <p>
              <a href="#" class="more">See All Popular <span class="icon-keyboard_arrow_right"></span></a>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6">
            <ul class="custom-pagination list-unstyled">
              <li><a href="#">1</a></li>
              <li class="active">2</li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section style= "margin:0px 200px; margin-top:80px;">
	<h1>{{post.title}}</h1>
    <br>
    <br>
    
    작성자 : {{post.writer}} <br>
    해시태그 : 
    {% for i in hashtag%}
        #{{i}}
    {%endfor%} <br>
    
    
    마감날짜 : {{post.deadline}} <br>

	{%if post.image%}
    	<p>사진 : <img src="{{post.image.url}}" alt="사진"></p>
    {%endif%}
    

    <p style="height:200px; word-wrap:break-word; overflow:scroll;">
	{{post.body}}
    </p>

    <span href="#" class="like" name="{{post.id}}" value="Like">

        <!-- 만약 유저가 좋아요를 눌렀다면 채운 하트로 변경 -->
        {% if user in post.like_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-heart" id="like-icon" style="color:black;"></i>
        </div>
        
        <!-- 아니면 비워진 하트 -->
        {% else %}

        <div class="alt-service-icon">
            <i class="far fa-heart" id="like-icon" style="color:black;"></i>
        </div>
        
        {% endif %}

        <span id="like-count-{{ post.id }}" class="alt-services-title font-alt">
            좋아요
            {% if post.like_count == 0 %}
            0개
            {% else %}
            {{ post.like_count }}개
            {% endif %}
        </span>
    </span>
	<br>
    <br>
	{% if user == post.writer %}
    <a href="{%url 'posts:edit_post' post.id%}" class="btn btn-dark">수정하기</a>
    <a href="{%url 'posts:delete' post.id%}" class="btn btn-dark">삭제하기</a>
	{%endif%}
	<hr>
    
</section>

<br>


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<script>
    $(".like").click(function () {
        var pk = $(this).attr('name')
        $.ajax({
            url: "{% url 'posts:like_toggle' post.pk %}",
            data: {
                'pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            type: "POST",
            dataType: "json",

            success: function (response) {

                if (response.like_count == null) {
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                } else {
                    if (response.result == "like") {
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart');
                    } else {
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart');
                    }

                    $('#like-count-{{ post.id }}').html('좋아요 ' + response.like_count + '개');
                }
            },

            error: function (request, status, error) {
                alert("로그인이 필요합니다.")
                alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" +
                    "error:" + error);
            },
        });
    })
    </script>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section style="margin:0px 200px; margin-top:80px;">
<h1> 게시물 수정하기 </h1><br>
	<form action="{%url 'posts:update' post.id%}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<p>제목 : <input value="{{post.title}}" type="text" name="title" required></p>
		<p>요약 태그 : <input style="width:500px;" value="{{post.title_tag}}" type="text" name="title_tag" required></p>
		<p>해시 태그 : <input style="width:500px;" value="{%for i in hashtag%}{{i}}&nbsp;{% endfor%}" type="text" name="hashtag" required></p>
		<p>마감기한 : <input value="{{deadline}}" type="datetime-local" name="deadline" required></p>
		<p>사진 : <input value="{{post.image}}" type="file" name="image">{{post.image}}</p>
		<p>내용 : <textarea style="width: 100%;" type="text" name="body" id="" cols="50" rows="10"
				required>{{post.body}}</textarea></p>
		<button type="submit">제출</button>
	</form>
</section>

<br>
<br>
{% endblock %}

posts/templates/posts/new_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section style="margin:0px 200px; margin-top:80px;">
<h1> 게시물 작성하기 </h1><br>
	<form action="{%url 'posts:create'%}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title" required></p>
		<p>요약 태그 : <input style="width:500px;" placeholder="이 활동을 요약해서 20자 안으로 설명해주세요" type="text" name="title_tag" required></p>
		<p>해시 태그 : <input style="width:500px;" placeholder="이 활동을 대표할 키워드를 적어주세요. 2개이상시 단어마다 띄워쓰기 부탁드립니다" type="text" name="hashtag" required></p>
		<p>마감기한 : <input type="datetime-local" name="deadline" required></p>
		<p>사진 : <input type="file" name="image"></p>
		<p>내용 : <textarea style="width: 100%;" type="text" name="body" id="" cols="50" rows="10"
				required></textarea></p>
		<button type="submit">제출</button>
	</form>
</section>

<br>
<br>
{% endblock %}

posts/templates/posts/postlist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12" >
            <div class="section-title">
              <h2><a style="color:black;" href="{% url 'posts:new_post' %}">글쓰기</a></h3>
              <div style="width:80%; text-align:right;">
              <a href="{% url 'posts:postlist' 1 %}">진행중</a> &nbsp;
              <a href="{% url 'posts:postlist' 2 %}">오늘 마감</a> &nbsp;
              <a href="{% url 'posts:postlist' 3 %}">지난거</a> &nbsp;
              </div> <br>
            </div>
            <div id="postlist" style="width:100%; justify-content:space-around;"></div>
            {% for post in posts %}
            
            <script  src="{% static 'js/jquery-latest.min.js'%}"></script>
            
            <script>
              function posting (){
                    var post_id = {{post.id}};
                    var hash = {{hashtag|safe}};
                    var html = "";
                    console.log(post_id);
                    var hashtag='<span class="d-block">';
                    for(var item in hash[post_id]){
                      hashtag+='#'+hash[post_id][item]+' ';
                    }
                    hashtag+='</span>';
                    html +=`
                    <div class="post-entry-2 d-flex"  >
                    <div class="thumbnail order-md-2" style="margin-right:50px;" >
                    {%if post.image%}
    	                <div style="height:200px; width:170px;"> <img style="width:100%; height:100%;" src="{{post.image.url}}" alt="사진"></div>
                    {%else%}
    	                <div style="height:200px; width:170px;"> <img style="width:100%; height:100%;" src="{% static 'images/d2.jpg' %}" alt="사진"></div>
                    {%endif%}
                    </div>
                    <div class="contents order-md-1 pl-0" style="width:70%; ">
                    <h2><a href="{% url "posts:detail" post.id %}">{{post.title}}</a></h2>
                    <p class="mb-3">{{post.body|truncatechars:30}}</p>
                    <div class="post-meta">
                    <span class="d-block">~{{post.deadline}}</span>
                    ${hashtag}
                    <span class="d-block">작성자 : {{post.writer}}</span>    <br>
                    <span style="box-shadow: rgba(0, 0, 0, 0.05) 0px 6px 24px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px; padding:3px; border:1px solid black;"><a href="{% url "users:addlist" post.id %}">To-do list 추가</a></span>
                    </div>
                    </div>
                    </div><hr>`;
                    
                    $("#postlist").append(html); 
                    
                  }
                  
                  posting();


            </script>
            {%endfor%}
                 
            
            
          
        </div>

        
      </div>
    </div>

{% endblock %}